- name: variables from prompt
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  - name: password
    prompt: what is your password?
    private: true    
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, username is: {{ username }}, Password is: {{ password }}"    

