- name: variables from files
  hosts: localhost
  connection: local
  tasks:
   - name: print course info
     ansible.builtin.debug:
       msg: "couse name is: {{ COURSE }}, duration: {{ DURATION }}, trainer: {{ TRAINER }}"