- name: variables from args
  hosts: localhost
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }}, duration: {{ DURATION }}, trainer: {{ TRAINER }}"