- name: loops 
  hosts: localhost
  connection: local
  tasks: 
  - name: print name
    ansible.builtin.debug:
     msg: "Hello {{ item }}" # item is a reserved keys
    loop:
    - Ramesh
    - Suresh
    - Raheem
    - John