- name: Install Packages
  hosts: localhost
  connection: local
  tasks:
  - name: print name
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip