- name: functions
  hosts: localhost
  connection: local
  vars:
     technologies: DevOps, Shell, Linux, Ansible  # string
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Pradeep') }}"


  # string to list
  - name: convert string to list
    ansible.builtin.debug:
     msg: "Technologies are: {{ technologies | split (',')}}"