- name: functions
  hosts: localhost
  connection: local
  vars:
     technologies: DevOps, Shell, Linux, Ansible  # string
     # dictionary == map
     tags:
       Application: Payments
       Environment: dev
     # Lists
     listTags:
     - key: Application
       value: payment
     - key: Environment
       value: dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Pradeep') }}"


  # string to list
  - name: convert string to list
    ansible.builtin.debug:
     msg: "Technologies are: {{ technologies | split (',')}}"


  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"


  - name: read yaml and take it into variables
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'path/to/your/student.yaml') | from_yaml }}"

  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student.yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student.yaml | to_nice_json }}"