 - name: functions
   hosts: localhost
   connection: local
   vars:
     technologies: DevOps, Shell, Linux, Ansible  # string
     name: "saipradeep reddy p"
     gmail: "INFO@gmail.COM"
     ipaddress: "191.89.73.1"
     # dictionary == map
     tags:
       Application: Payments
       Environment: dev
     # Lists
     listTags:
     - key: Application
       value: payment
     - key: Environment
       value: dev
   tasks:
   - name: default variables
     ansible.builtin.debug:
      msg: "Hello {{ name | default('Pradeep') }}"


  # string to list
   - name: convert string to list
     ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split (',')}}"


   - name: convert map to list
     ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

   - name: convert list into map
     ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"


   - name: read yaml and take it into variable
     ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

   - name: convert yaml into json
     ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json }}"

   - name: save json to file
     ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"


   - name: convert into uppercase
     ansible.builtin.debug:
       msg: "{{ name | upper }}"

   - name: convert lowercase
     ansible.builtin.debug:
       msg: "{{ gmail | lower }}"

   - name: check the valid ip or not
     ansible.builtin.debug:
       msg: "{{ ipaddress | ansible.utils.ipv4 }}"




       # IF u want check ipaddress need install netaddr ---> ansible --version
       # check python version Am installing pip3.9 install netaddr 


   - name: grep for root
     ansible.builtin.shell: cat /etc/passwd | grep root
     register: command_output


   - name: print the command_output
     ansible.builtin.debug:
       msg: "{{ command_output }}"

   - name: redirect the output
     ansible.builtin.command:  ls -ltr > /tmp/output.txt
     register: redirect_output

   - name: print the redirect_output
     ansible.builtin.debug:
       msg: "{{  redirect_output }}"